[project]
name = "streamlit-web-scraper-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "openai>=1.109.0",
    "requests>=2.32.5",
]
